// Code generated by "stringer -type FileAttributeType -trimprefix Attribute"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttributeBitrate-0]
	_ = x[AttributeDuration-1]
	_ = x[AttributeVBR-2]
	_ = x[AttributeSampleRate-4]
	_ = x[AttributeBitDepth-5]
}

const (
	_FileAttributeType_name_0 = "BitrateDurationVBR"
	_FileAttributeType_name_1 = "SampleRateBitDepth"
)

var (
	_FileAttributeType_index_0 = [...]uint8{0, 7, 15, 18}
	_FileAttributeType_index_1 = [...]uint8{0, 10, 18}
)

func (i FileAttributeType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _FileAttributeType_name_0[_FileAttributeType_index_0[i]:_FileAttributeType_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _FileAttributeType_name_1[_FileAttributeType_index_1[i]:_FileAttributeType_index_1[i+1]]
	default:
		return "FileAttributeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
