// Code generated by "stringer -type UploadPermission -trimprefix Permission"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionNoOne-0]
	_ = x[PermissionEveryone-1]
	_ = x[PermissionUsersInList-2]
	_ = x[PermissionPermittedUsers-3]
}

const _UploadPermission_name = "NoOneEveryoneUsersInListPermittedUsers"

var _UploadPermission_index = [...]uint8{0, 5, 13, 24, 38}

func (i UploadPermission) String() string {
	if i < 0 || i >= UploadPermission(len(_UploadPermission_index)-1) {
		return "UploadPermission(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UploadPermission_name[_UploadPermission_index[i]:_UploadPermission_index[i+1]]
}
