// Code generated by "stringer -type Code -trimprefix Code"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeLogin-1]
	_ = x[CodeLoginFailed-1]
}

const _Code_name = "Login"

var _Code_index = [...]uint8{0, 5}

func (i Code) String() string {
	i -= 1
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
