name: Test Suite

on:
  push:
    branches: [ "main" ]

jobs:
  testsuite:
    runs-on: ubuntu-latest

    services:
      soulfind:
        image: ghcr.io/soulfind/server:latest
        ports:
          - "2242:2242"
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test suite
      run: go test -parallel 100 --cover -covermode=atomic -coverpkg=./... ./... -coverprofile=coverage.txt	

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}