name: Unit Suite

on:
  push:
    branches: [ "master" ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Unit tests
      run: go test -short -race -count 10 -parallel 10 --cover -covermode=atomic -coverpkg=./... ./...
